name: quit_smoke
description: Quit Smoking Now!

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  shared_preferences: null
  sqflite: null
  path_provider: ^1.6.21
  lottie: ^0.6.0
  url_launcher: ^5.7.5
  avatar_glow: ^1.2.0
  cached_network_image: ^2.3.3
  permission_handler: null

  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2
  google_sign_in: ^4.5.5
  firebase_core: ^0.5.0+1
  flare_flutter: ^2.0.6
  getwidget: ^1.2.2
  flutter_offline: ^0.3.0
  google_fonts: ^1.1.0
  focus_widget: ^1.0.4+1
  toast: ^0.1.5
  intl: ^0.16.1
  connectivity: ^0.4.9+5
  date_time_format: ^1.1.0
  flutter_datetime_picker: ^1.4.0
  dots_indicator: ^1.2.0
  hive: ^1.4.4+1
  # introduction_screen: ^1.0.9
  # datetime_picker_formfield: ^1.0.0
  # dependency_overrides:
  # flutter_offline:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
  fonts:
    - family: Abril
      fonts:
        - asset: assets/fonts/Abril/Abril-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro/SourceSansPro-Regular.ttf

